application: votametro
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /images
  static_dir: images

- url: /text
  static_dir: text

- url: /robots.txt
  script: _go_app

- url: /
  script: _go_app

- url: /help
  script: _go_app

- url: /doxml.xml
  script: _go_app

- url: /.*
  script: _go_app
  login: required
  secure: always

